version: '3'

services:
  web-server:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist/client:/var/www/html
   
  subscription-db:
    image: mongo:3.6.15
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
        - vol-db:/data/db

  subscription-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    links:
      - subscription-db
    depends_on:
      - subscription-db
    volumes:
      - ./server:/home/app
    environment:
      - DB=subscription
      - DB_SERVERS=subscription-db:27017

volumes:
  vol-db:

    